version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running tests...
      - npm test
      - echo Packaging Lambda...
      # If index.js is already at repo root, no copy needed
      - zip -r build.zip index.js node_modules package.json

  post_build:
    commands:
      - echo Deploying to Lambda...
      # Replace with your actual Lambda function name
      - aws lambda update-function-code --function-name package-function --zip-file fileb://build.zip

artifacts:
  files:
    - build.zip
